spring:
 threads:
  virtual:
   enabled: true
 rabbitmq:
  addresses: localhost
  port: 5672
  username: guest
  password: guest
 datasource:
  url: jdbc:postgresql://localhost:5432/batch_db
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
management:
 endpoints:
  web:
   exposure:
    include: "*"
app:
 datasource:
  url: jdbc:postgresql://localhost:5432/batch_db
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
