spring:
 batch:
  datasource:
   url: jdbc:postgresql://localhost:5432/batch_metadata_db
   username: postgres
   password: root
    driver-class-name: org.postgresql.Driver
  jdbc:
   initialize-schema: always
 sql:
  init:
   mode: always
